/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0d0e11",
        "on-background": "#e3e2e6",
        "on-primary-fixed-variant": "#274776",
        "primary-container": "#1a3c6b",
        "on-secondary-container": "#003f4e",
        "surface-container-high": "#292a2d",
        "on-tertiary-container": "#95a8c4",
        "on-primary-container": "#89a7dd",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#2b3d54",
        "tertiary-fixed-dim": "#b5c8e5",
        "primary": "#a9c7ff",
        "inverse-surface": "#e3e2e6",
        "surface-container": "#1e2023",
        "on-surface-variant": "#c4c6d0",
        "surface-tint": "#a9c7ff",
        "surface-dim": "#121317",
        "on-tertiary-fixed-variant": "#364860",
        "on-error": "#690005",
        "surface-container-highest": "#333538",
        "on-secondary-fixed": "#001f27",
        "secondary-fixed-dim": "#4cd6fb",
        "on-tertiary": "#1f3148",
        "surface-variant": "#333538",
        "on-surface": "#e3e2e6",
        "on-secondary": "#003642",
        "on-tertiary-fixed": "#081c32",
        "secondary": "#4cd6fb",
        "on-primary": "#09305f",
        "tertiary": "#b5c8e5",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed": "#d2e4ff",
        "outline": "#8d909a",
        "background": "#121317",
        "inverse-on-surface": "#2f3034",
        "secondary-container": "#00b2d6",
        "inverse-primary": "#405f90",
        "secondary-fixed": "#b3ebff",
        "surface-container-low": "#1a1c1f",
        "outline-variant": "#43474f",
        "surface": "#121317",
        "error-container": "#93000a",
        "primary-fixed-dim": "#a9c7ff",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#004e5f",
        "surface-bright": "#38393d",
        "on-primary-fixed": "#001b3d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        "stack-xl": "64px",
        "margin": "24px",
        "container-max": "1440px",
        "stack-xs": "4px",
        "unit": "4px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "h2": ["Space Grotesk"],
        "label": ["Inter"],
        "h3": ["Space Grotesk"],
        "h1": ["Space Grotesk"],
        "data-lg": ["Space Grotesk"],
        "data-sm": ["Space Grotesk"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.3", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "data-lg": ["20px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "data-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}

